name: Cypress End-to-end Tests on Chrome

on: [push]

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6 
        with:
          build: npm run build
          start: npm start
          browser: chrome
